read: AGENTS.md

git: false

dark-mode: true

vim: true

alias:
  - "openai:gpt-5"
  - "anthropic:claude-sonnet-4-5"
  - "google:gemini-2.5-pro"
  - "gpt:gpt-5"
  - "claude:claude-sonnet-4-5"
  - "gemini:gemini-2.5-pro"
  - "xai:xai/grok-4-0709"
  - "perplexity:perplexity/sonar-reasoning"